version: "3.8"
services:
  web:
    build:
      context: ./
      target: dev
    volumes:
      - .:/app
    command: yarn run dev
    ports:
      - "8880:8880"
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*
